# ch6. Application / DataSet 's Tips


## 1. Application Tips
- Learning Rate 값의 조정
- Data Preprocessing (데이터 전처리)
- Over Fitting 의 방지

### 01) Learning Rate
- 데이터/ 환경에 따라 각기 고유값을 정한다 (정해진 답은 없다)

<p> 다양한 learning rate을 사용해서 여러 번에 걸쳐 실행하는 것이 최선<br/>
  cost가 거꾸로 증가하는 overshooting 현상과 너무 조금씩 감소하는 현상 확인<br/>

출처: http://pythonkim.tistory.com/23 [파이쿵] </p>
<img src='./img/lec_07_01.png' align="left">

### 02) Data Preprocessing (데이터 전처리)
- 데이터정규화를 통한 전처리

<img src='./img/lec_07_07.png' align="left" width=600>

<img src='./img/lec_07_08.png' align="left">

<img src='./img/lec_07_09.png' align="left">

<p> https://brunch.co.kr/@rapaellee/4  길지 않게 잘 설명<br/>    
  Standardization<br/>
  수식 : (요소값 - 평균) / 표준편차<br/>
  설명 : 평균까지의 거리로, 2개 이상의 대상이 단위가 다를 때, 대상 데이터를 같은 기준으로 볼 수 있게 해줌<br/>

  Normalization<br/>
  수식 : (요소값 - 최소값) / (최대값 - 최소값)<br/>
  설명 : 전체 구간을 0~100으로 설정하여 데이터를 관찰하는 방법으로, 특정 데이터의 위치를 확인할 수 있게 해줌<br/>

김성훈 교수님은 standardization에 대해 설명하셨고, <br/>
앤드류 교수님은 normalization에 대해 설명하셨다. 그래서, 두 가지 모두 중요한 방법이다.

출처: http://pythonkim.tistory.com/23 [파이쿵]

### 03) OverFitting 피하기
- More Training Data! (더 많은 트레이닝데이터 입력하기)
- Reduce the Number of Features ( 중복되는 자료 제거 )
- Regularization (일반화 모형으로 만들기)

<img src = "./img/lec_07_11.png" align="left">

Cost Loss 함수의 뒤에  
$W^2$ 의 값을 작게 만드는 수식을 추가

<img src="./img/lec_07_14.png" align="left">

## 2. DataSet

### 01) DataSet

<p><h2>데이터 테이블 전체 중</h2></p></br>
<p><strong>일부를</strong> : 훈련 데이터</p></br>
<p><strong>나머지 중 일부를</strong> : 확인 데이터 로 활용</p></br>

<img src ="./img/lec_07_19.png" align="left">

<img src ="./img/lec_07_18.png" align="left">

### 02) On line Learning

<p> Data Set 이, 시간의 흐름에 따라 추가</p></br>

<img src = "./img/lec_07_20.png" align ="left">

<p> tensorflow 계열에서는 가장 유명하다.<br/>
(가장 신뢰할 수 있는 데이터로 어디서나 mnist 데이터셋을 사용하고 있었다.)</p>

mnist는 우편번호의 자동분류 데이터셋이다. 
1. 글자 하나의 크기는 28x28이고, 
2. 모두 흑백으로 되어 있다. 
3. 데이터셋은 image와 label로 구분되어 있고,<br/> 
   각각은 다시 train과 test로 나누어져 있다. 
4. validation set은 보이지 않는데, tensorflow 예제를 분석하다 보면 만날 수 있다.<br/>
(이미지 분류 샘플이면서, 흑백이어서 GPU가 없이도 돌려볼 수 있다.)

출처: http://pythonkim.tistory.com/26 [파이쿵]<br/>
<img src="./img/lab_07_06.png" align = "left">

## 3. Training and Test DataSets 구분 Source

### 01) DataSet & TestSets

In [19]:
import tensorflow as tf
X = tf.placeholder("float", [None, 3])
Y = tf.placeholder("float", [None, 3])
W = tf.Variable(tf.random_normal([3,3]))
b = tf.Variable(tf.random_normal([3]))

In [20]:
hypothesis = tf.nn.softmax(tf.matmul(X, W)+b)
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

In [21]:
# Test 모델을 정의
prediction = tf.arg_max(hypothesis, 1)
is_correct = tf.equal(prediction, tf.arg_max(Y,1))  # 자료의 정확도 측정함수
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

In [22]:
## input Tensor ----------------------------------------
# Data Sets
x_data = [[1, 2, 1], [1, 3, 2], [1, 3, 4], [1, 5, 5],
          [1, 7, 5], [1, 2, 5], [1, 6, 6], [1, 7, 7]]
y_data = [[0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 1, 0],
          [0, 1, 0], [0, 1, 0], [1, 0, 0], [1, 0, 0]]
# Evaluation our model using this test dataset
x_test = [[2, 1, 1], [3, 1, 2], [3, 3, 4]]
y_test = [[0, 0, 1], [0, 0, 1], [0, 0, 1]]

In [23]:
## Launch Graph
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [24]:
# /t 탭간격, /n 줄바꿈
for step in range(201):
    if step % 40 == 0:
        cost_val, W_val , _ = sess.run([cost, W, optimizer], feed_dict={X:x_data, Y:y_data})
        print("Step:  {:2}\tCost: {:.3f}\nW: {:}".format(step, cost_val, W_val))

Step:   0	Cost: 4.978
W: [[ 1.34817994 -0.09998062  0.40574202]
 [ 0.50776923 -0.77081567 -0.14448722]
 [ 0.48796618 -0.15759198  0.5071277 ]]
Step:  40	Cost: 3.911
W: [[ 1.30096769 -0.06278512  0.41575882]
 [ 0.3140654  -0.59648538 -0.12511368]
 [ 0.30733338  0.02944982  0.50071871]]
Step:  80	Cost: 2.760
W: [[ 1.28702986 -0.02619098  0.3931025 ]
 [ 0.27829653 -0.42367014 -0.26216   ]
 [ 0.28589588  0.21510302  0.33650303]]
Step:  120	Cost: 1.769
W: [[ 1.25230706  0.00722218  0.39441219]
 [ 0.13555336 -0.26021391 -0.28287306]
 [ 0.15798689  0.39001527  0.28949976]]
Step:  160	Cost: 1.001
W: [[ 1.24440026  0.02233728  0.38720393]
 [ 0.12920752 -0.17986009 -0.35688105]
 [ 0.16393058  0.4778091   0.19576225]]
Step:  200	Cost: 0.901
W: [[ 1.23951507  0.01338161  0.40104485]
 [ 0.14418687 -0.21682322 -0.33489728]
 [ 0.18981014  0.44469878  0.20299301]]


In [25]:
sess.close()

### 02) Adjusting Learning Rates
- Cost 값이 적절하게 잘 변화가능한, Learning Rate 값을 임의로 찾는다.<br/><br/>
<img src="./img/lab_07_03.png" align = "left">

### 03) Non - Nomalized inputs
- 자료의 정규화를 통한 전처리

#### 01> 정규화 하기 전

In [8]:
import tensorflow as tf
import numpy as np
X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, 1])
W = tf.Variable(tf.random_normal([4, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [9]:
# Hypothesis
hypothesis = tf.matmul(X, W) + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))
# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Inputing Tensor -------------------------------------------------------
xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])

In [10]:
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

In [11]:
# Launch the graph in a session.
sess = tf.Session()
sess.run(tf.global_variables_initializer())
for step in range(101):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)
sess.close()

0 Cost:  0.799205 
Prediction:
 [[ 0.47259724]
 [ 0.23193526]
 [-0.15399647]
 [-0.56403172]
 [-0.3167944 ]
 [-0.42378223]
 [-1.04098082]
 [-1.08785522]]
1 Cost:  0.799157 
Prediction:
 [[ 0.47263515]
 [ 0.23197353]
 [-0.15396416]
 [-0.56400603]
 [-0.31676453]
 [-0.42375326]
 [-1.04095984]
 [-1.08783412]]
2 Cost:  0.799109 
Prediction:
 [[ 0.47267306]
 [ 0.23201168]
 [-0.15393174]
 [-0.56398028]
 [-0.31673479]
 [-0.42372435]
 [-1.04093874]
 [-1.0878129 ]]
3 Cost:  0.799061 
Prediction:
 [[ 0.47271097]
 [ 0.23204994]
 [-0.15389931]
 [-0.56395459]
 [-0.31670499]
 [-0.42369545]
 [-1.04091763]
 [-1.0877918 ]]
4 Cost:  0.799012 
Prediction:
 [[ 0.47274888]
 [ 0.23208821]
 [-0.15386701]
 [-0.56392884]
 [-0.31667519]
 [-0.42366642]
 [-1.04089665]
 [-1.0877707 ]]
5 Cost:  0.798964 
Prediction:
 [[ 0.47278678]
 [ 0.23212647]
 [-0.15383458]
 [-0.56390309]
 [-0.31664538]
 [-0.42363757]
 [-1.04087555]
 [-1.0877496 ]]
6 Cost:  0.798916 
Prediction:
 [[ 0.47282469]
 [ 0.23216474]
 [-0.15380228]
 [-0.

#### 02> 정규화 이후의 연산
def MinMaxScaler(data):<br/>
... numerator = data - np.min(data, 0)<br/>
... denominator = np.max(data, 0) - np.min(data, 0)<br/>
... return numerator / (denominator + 1e-7)<br/>

In [6]:
xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])

In [7]:
# very important. It does not work without it.
tf.set_random_seed(777)  # for reproducibility
def MinMaxScaler(data):
    numerator = data - np.min(data, 0)               # numerator : 분자
    denominator = np.max(data, 0) - np.min(data, 0)  # denominator : 분모
    # noise term prevents the zero division
    return numerator / (denominator + 1e-7)

xy = MinMaxScaler(xy)
print(xy)

[[ 0.99999999  0.99999999  0.          1.          1.        ]
 [ 0.70548491  0.70439552  1.          0.71881782  0.83755791]
 [ 0.54412549  0.50274824  0.57608696  0.606468    0.6606331 ]
 [ 0.33890353  0.31368023  0.10869565  0.45989134  0.43800918]
 [ 0.51436     0.42582389  0.30434783  0.58504805  0.42624401]
 [ 0.49556179  0.42582389  0.31521739  0.48131134  0.49276137]
 [ 0.11436064  0.          0.20652174  0.22007776  0.18597238]
 [ 0.          0.07747099  0.5326087   0.          0.        ]]
