# ch9. Nural Network  For  XOR
- http://pythonkim.tistory.com/33

## 1. XOR 문제의 해결

<p> 단일 Logistic Regression 으로는 해결할수 없음이 수학적으로 증명</p></br>
<p> Logistic을 3개를 연결 후, forward, backward 로 해결하는 방안을 발표 </p></br>
<img src="./img/lab09-1.jpg" align="left" width=300>

<p> Nural Network 구성도 </p></br></br>
<img src="./img/lec_09_07.png" align="left">

<p> 숫자 대입을 통한 증명 </p></br></br>
<img src="./img/lec_09_05.png" align="left">

<p> TensorFlow 를 통한 Nural Network  </p></br></br>
<img src="./img/lec_09_09.png" align="left">

## 2.Basic Derivative (미분의 기초)

### 01) Derivative (미분)


<p> < $ \frac{d}{dx}f(x) $ = 함수 결과값($f(x)$) 과 $wX$ 변수간의 변화율 > </p></br>
<p> $ f(x) = 3 (상수) $ : $ \frac{d}{dx}f(x) = 0$ </p></br>
<p> $ f(x) = x $ : $ \frac{d}{dx}f(x) = 1$ </p></br>
<p> $ f(x) = 2x $ : $ \frac{d}{dx}f(x) = 2$ </p></br>

<img src="./img/lec_09_10.png" align="left">

### 02) Partial derivative (편미분)
- $ \frac{d}{dx}$ 에서 $x$ 를 제외한 나머지 <strong>변수</strong>는 상수로 취금

<p> $ f(x,y) = 2x = (x + x) $ = $ (\frac{df}{dx} +\frac{df}{dx}) $ = ( 1 + 1 ) = 2 </p></br>
<p> $ f(x,y) = xy $ : $ \frac{df}{dx}f(x) = y$ , $ \frac{df}{dy}f(x) = x$ ,  </p></br>
<p> $ f(x,y) = x + y $ : $ \frac{df}{dy}f(x) = x + 0 = 1$ , $ \frac{df}{dx}f(x) = 0 + y = 1$ ,  </p></br>

## 3. Hyphothesis & Cost/ Loss function 적용
- http://pythonkim.tistory.com/36

<p> $ H(x) = Sigmoid(z) $<t>&nbsp;&nbsp;&nbsp;</t> $ z = wX + b $ </p></br> 
<p> $ \frac{df}{dx} = \frac{df}{dg} * \frac{dg}{dx} $ (각 각의 미분 곱) </p></br>
<p> 하지만 연결갯수가 많으면, 연산시 곤란한 경우가 많다 </p>
<img src="./img/lec_09_15.png" align="left">
<img src="./img/lec_09_16.png" align="left" width=518>

## 4. Chain Rule 
- Back Propagation 의 원할한 적용을 위해, 수식이 아닌 변수별 미분을 계산 후 적용

<img src="./img/lec_09_18.png" align="left">

<img src="./img/lec_09_21.png" align="left">

## 5. Sigmoid 함수에 적용
g(z)를 풀어보면 위의 그림이 나오고, 말로 하면 아래처럼 된다.

  1. z에 -1을 곱해서 음수로 만든다.
  2. exp(지수)를 계산한다.
  3. 1을 더한다.
  4. 앞의 결과를 분모로 취한다. (1/x)


출처: http://pythonkim.tistory.com/36 [파이쿵]
<p></p></br></br></br>
<img src="./img/lec_09_22.png" align="left">

## 6. Back Propagation in TensorFlow
<p></p></br></br></br>
<img src="./img/lec_09_24.png" align="left">

<img src="./img/lec_09-02.jpg" align="left" width=450>

## 7. TensorFlow Coding
- http://pythonkim.tistory.com/37

### 01) Logistic regression 을 활용한  XOR ( 해결 불가능)

In [4]:
import tensorflow as tf
import numpy as np
X = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

In [5]:
xy = np.loadtxt('./data/07train.txt', unpack=True)
x_data = xy[0:-1]  # column을 기준으로 Slicing
y_data = xy[-1]
xy

array([[ 0.,  0.,  1.,  1.],
       [ 0.,  1.,  0.,  1.],
       [ 0.,  1.,  1.,  0.]])

In [6]:
# W 값은 x1, x2... 의 갯수에 맞워서 설정,   범위지정 ( -1.0 , 1.0 )
W = tf.Variable(tf.random_uniform([1, len(x_data)], -1.0, 1.0)) 
h = tf.matmul(W, X)

In [7]:
# Hypothesis / Cost,Loss Function (Cross Entropy)
hypothesis = tf.div(1., 1. + tf.exp(-h))
cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) * tf.log(1 - hypothesis))
rate = tf.Variable(0.1)

In [8]:
optimizer = tf.train.GradientDescentOptimizer(rate)
train = optimizer.minimize(cost)

In [9]:
#init = tf.initialize_all_variables()
init = tf.global_variables_initializer()

In [ ]:
# With 문 밖에서 실행하면 오류가 발생한다.. Why????
# print('Accuracy :', accuracy.eval({X:x_data, Y:y_data}))

In [10]:
with tf.Session() as sess:
    sess.run(init)
    for step in range(1000):
        sess.run(train, feed_dict={X: x_data, Y: y_data})
        if step % 200 == 0:
            print("Step :",step,"Cost :",sess.run(cost, feed_dict={X: x_data, Y: y_data}),"W :",sess.run(W))
    print('-'*50)
    # Test model --( "hypothesis 값이 0.5 보다 크면 1을 출력 | 작으면 0을 출력 )
    correct_prediction = tf.equal(tf.floor(hypothesis+0.5), Y)
    # Calculate Accuraty ----------------------------------------
    accuracy = tf.reduce_mean(tf.cast(correct_prediction, 'float'))
    #            [ 가설결과값   ,  가설결과를  1|0 로 변환  ,   실측값과 비교       ,    정확도  ]
    # sess.run([hypothesis, tf.floor(hypothesis+0.5), correct_prediction, accuracy], feed_dict={X:x_data, Y:y_data})
    param = [hypothesis, tf.floor(hypothesis+0.5), correct_prediction, accuracy]
    result = sess.run(param, feed_dict={X:x_data, Y:y_data})
    for i in result:
        print(i)
    print('Accuracy :', accuracy.eval({X:x_data, Y:y_data}))

Step : 0 Cost : 0.723344 W : [[ 0.06424129 -0.7320224 ]]
Step : 200 Cost : 0.693983 W : [[ 0.10701776 -0.1226778 ]]
Step : 400 Cost : 0.693214 W : [[ 0.03261442 -0.03297038]]
Step : 600 Cost : 0.693153 W : [[ 0.00935474 -0.00936282]]
Step : 800 Cost : 0.693148 W : [[ 0.00267076 -0.00267094]]
--------------------------------------------------
[[ 0.5         0.49980825  0.50019175  0.5       ]]
[[ 1.  0.  1.  1.]]
[[False False  True False]]
0.25
Accuracy : 0.25


### 02) Nural Network 의 Layer를 활용한  XOR

In [1]:
import tensorflow as tf
X = tf.placeholder(tf.float32, [None, 2])
Y = tf.placeholder(tf.float32, [None, 1])

<img src = "./img/lab_09_05.png" align="left">

In [2]:
# Hypothesis 01 ----------------------------------
W1 = tf.Variable(tf.random_normal([2, 2]), name='weight1')
b1 = tf.Variable(tf.random_normal([2]), name='bias1')
# Hypothesis 02 ----------------------------------
W2 = tf.Variable(tf.random_normal([2, 1]), name='weight2')
b2 = tf.Variable(tf.random_normal([1]), name='bias2')

In [3]:
# Hypothesis 01 / 02 연결
# layer1 : W1과 W2 연결링크
layer1 = tf.sigmoid(tf.matmul(X, W1) + b1)
hypothesis = tf.sigmoid(tf.matmul(layer1, W2) + b2)

In [4]:
# cost/loss function
cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) * tf.log(1 - hypothesis))
train = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

In [ ]:
# Accuracy computation
# (0, 1의 값으로 치환) True if hypothesis > 0.5 else False  (0.5를 기준 True/False)  cf) sigmoid 는 (0이 기준) 
predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
# accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

In [5]:
# Calculate Accuraty ----------------------------------------
correct_prediction = tf.equal(tf.floor(hypothesis+0.5), Y)
accuracy = tf.reduce_mean(tf.cast(correct_prediction, 'float'))

In [6]:
# Inputing Tensor -----------------------------------------------------------
import numpy as np
tf.set_random_seed(777)  # for reproducibility
x_data = np.array([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=np.float32)
y_data = np.array([[0], [1], [1], [0]], dtype=np.float32)

In [7]:
# Launch graph --------------------------------------------------------------
sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(10001):
    sess.run(train, feed_dict={X: x_data, Y: y_data})
    if step % 2500 == 0:
        print("Step:", step, "Cost:", sess.run(cost, feed_dict={
              X: x_data, Y: y_data}), "\n Run (W1):" ,"\n" , sess.run(W1),"\n Run (W2):" ,"\n", sess.run(W2))

Step: 0 Cost: 1.67573 
 Run (W1): 
 [[ 0.45435488  1.90757763]
 [ 2.49049306 -0.31131512]] 
 Run (W2): 
 [[-0.9618476]
 [-0.3904123]]
Step: 2500 Cost: 0.455303 
 Run (W1): 
 [[ 3.19586134  2.77109623]
 [ 4.13764858 -3.76263928]] 
 Run (W2): 
 [[ 3.00797892]
 [ 3.04310775]]
Step: 5000 Cost: 0.374748 
 Run (W1): 
 [[ 4.09495497  3.72429633]
 [ 6.05614042 -5.93587446]] 
 Run (W2): 
 [[ 4.40109062]
 [ 4.8988018 ]]
Step: 7500 Cost: 0.361454 
 Run (W1): 
 [[ 4.41272259  4.07868767]
 [ 6.94131327 -6.8301568 ]] 
 Run (W2): 
 [[ 5.02457237]
 [ 5.64771986]]
Step: 10000 Cost: 0.356487 
 Run (W1): 
 [[ 4.59705591  4.2829361 ]
 [ 7.49655294 -7.37908649]] 
 Run (W2): 
 [[ 5.41629553]
 [ 6.10405207]]


In [191]:
# Accuracy report
h, c, cp, a = sess.run([hypothesis, predicted, correct_prediction, accuracy],
                   feed_dict={X: x_data, Y: y_data})    
print("\nHypothesis: ", h, "\nCorrect: ", c,"\nCheck: ", cp,"\nAccuracy: ", a)


Hypothesis:  [[ 0.01188578]
 [ 0.98649675]
 [ 0.98649931]
 [ 0.02103897]] 
Correct:  [[ 0.]
 [ 1.]
 [ 1.]
 [ 0.]] 
Check:  [[ True]
 [ True]
 [ True]
 [ True]] 
Accuracy:  1.0


In [192]:
sess.close()

### 03) Nural Network 의 Layer를 활용한  XOR 2   Widely!!

In [193]:
import tensorflow as tf
X = tf.placeholder(tf.float32, [None, 2])
Y = tf.placeholder(tf.float32, [None, 1])

In [ ]:
# Layer 를 연결시 주의할 점
# W1 의 [ alpha'n', Beta1 ]  W2 의 [ alpha2, Beta2] ..... 일때
# Beta1 == alpha2 조건만 맞추면서 연결을 해야 한다

<img src = "./img/lec-0920.png" align="left" width=700>

In [194]:
# Hypothesis 01
W1 = tf.Variable(tf.random_normal([2, 10]), name='weight1')
b1 = tf.Variable(tf.random_normal([10]), name='bias1')
# Hypothesis 02
W2 = tf.Variable(tf.random_normal([10, 10]), name='weight2')
b2 = tf.Variable(tf.random_normal([10]), name='bias2')
# Hypothesis 03
W3 = tf.Variable(tf.random_normal([10, 10]), name='weight3')
b3 = tf.Variable(tf.random_normal([10]), name='bias3')
# Hypothesis 04
W4 = tf.Variable(tf.random_normal([10, 1]), name='weight4')
b4 = tf.Variable(tf.random_normal([1]), name='bias4')

In [195]:
# Hypothesis가 4개 연결시, 연결 Layer는 3개
layer1 = tf.sigmoid(tf.matmul(X, W1) + b1)
layer2 = tf.sigmoid(tf.matmul(layer1, W2) + b2)
layer3 = tf.sigmoid(tf.matmul(layer2, W3) + b3) 
hypothesis = tf.sigmoid(tf.matmul(layer3, W4) + b4)

In [196]:
# cost/loss function
cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) * tf.log(1 - hypothesis))
train = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)
# Accuracy computation
# True if hypothesis>0.5 else False
predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)

In [197]:
# Calculate Accuraty ----------------------------------------
# accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))
correct_prediction = tf.equal(tf.floor(hypothesis+0.5), Y)
accuracy = tf.reduce_mean(tf.cast(correct_prediction, 'float'))

In [198]:
# Launch graph ----------------------------------------------------------------
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [199]:
# Inputing Tensor -------------------------
import numpy as np
tf.set_random_seed(777)  # for reproducibility
x_data = np.array([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=np.float32)
y_data = np.array([[0], [1], [1], [0]], dtype=np.float32)

In [200]:
for step in range(10001):
    sess.run(train, feed_dict={X: x_data, Y: y_data})
    if step % 2500 == 0:
        print("Step:",step, "Cost:", sess.run(cost, feed_dict={
              X: x_data, Y: y_data}), "\nRun(W1):",sess.run(W1),"\nRun(W2):",sess.run(W2))

Step: 0 Cost: 0.699468 
Run(W1): [[ 0.8255766   0.11741684 -0.37857988  0.03720431 -0.16897374  0.06273444
  -0.45793277 -0.64736688  0.1191975   0.56422961]
 [-0.6582796  -1.44163287 -1.65199482 -0.62886155 -0.6099205  -0.79839098
   1.81451118  1.15398788  0.79301912 -0.32405707]] 
Run(W2): [[ 0.26021865  1.08286452 -0.34417772  0.68993306  2.07101345  1.31702328
   0.53171605  0.36783499 -1.76340747  0.49645901]
 [-1.28458571  1.67629504  0.07772854  0.69253516  0.89586341  0.84895229
  -0.98565137 -0.71070445 -1.09179044  0.05667585]
 [ 0.55054748 -1.08216381 -1.07649922 -0.42474654 -1.28795838 -0.37219256
  -0.96133071  0.8322953   1.07704258 -0.37373456]
 [ 0.37147674  0.4206098  -0.11292756 -0.2099696   0.06636294 -1.01685238
  -1.59421051  0.65487713 -0.03577053  1.49644411]
 [ 0.16753438 -0.07063635  0.88377374  0.00506692 -1.29968488 -2.50376225
   0.61387986 -0.26480421  0.14375317 -0.19888981]
 [ 0.93069553  0.17624846  0.21177645  0.25446764  1.01522756 -0.05360224
   0.01

In [201]:
# Accuracy report
h, c, cp, a = sess.run([hypothesis, predicted, correct_prediction, accuracy],
                   feed_dict={X: x_data, Y: y_data})
print("\nHypothesis: ", h, "\nCorrect: ", c, "\nCheck: ", cp, "\nAccuracy: ", a)


Hypothesis:  [[ 0.0018599 ]
 [ 0.99830532]
 [ 0.99800247]
 [ 0.00195833]] 
Correct:  [[ 0.]
 [ 1.]
 [ 1.]
 [ 0.]] 
Check:  [[ True]
 [ True]
 [ True]
 [ True]] 
Accuracy:  1.0


In [202]:
sess.close()